package com.devintensive.devintensive.utils;


public interface ConstantManager {

    String TAG_PREFIX="DEV ";
    String COLOR_MODE_KEY = "COLOR_MODE_KEY";

    String EDIT_MOD_KEY="EDIT_MOD_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_EMAIL_KEY = "USER_EMAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_ABOUT_KEY = "USER_ABOUT_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";

    String USER_ID_KEY = "USER_ID_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";

    String USER_RATING_VALUE ="USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE ="USER_CODE_LINES_VALUE";
    String USER_PROJECTS_VALUE ="USER_PROJECTS_VALUE";

    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE =99;
    int REQUEST_GALLERY_PICTURE = 88;

    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMER_REQUEST_PERMISSION_CODE = 102;

}
